Repository raymag/floesia, pull requests merged in 2020-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: documentation

#4 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5 Update README.md
  README.md
Labels: documentation

#7 Base Organizacional do HTML/CSS
  CSS/index.css
  HTML/index.html
Labels: enhancement

#9 mudanças no HTML e inclusão do Bootstrap
  CSS/css_bootstrap/.DS_Store
  CSS/css_bootstrap/bootstrap-grid.css
  CSS/css_bootstrap/bootstrap-grid.css.map
  CSS/css_bootstrap/bootstrap-grid.min.css
  CSS/css_bootstrap/bootstrap-grid.min.css.map
  CSS/css_bootstrap/bootstrap-reboot.css
  CSS/css_bootstrap/bootstrap-reboot.css.map
  CSS/css_bootstrap/bootstrap-reboot.min.css
  CSS/css_bootstrap/bootstrap-reboot.min.css.map
  CSS/css_bootstrap/bootstrap.css
  CSS/css_bootstrap/bootstrap.css.map
  CSS/css_bootstrap/bootstrap.min.css
  CSS/css_bootstrap/bootstrap.min.css.map
  HTML/index.html
  Imagens/pre_logo.png
  js/bootstrap.bundle.js
  js/bootstrap.bundle.js.map
  js/bootstrap.bundle.min.js
  js/bootstrap.bundle.min.js.map
  js/bootstrap.js
  js/bootstrap.js.map
  js/bootstrap.min.js
  js/bootstrap.min.js.map
Labels: enhancement, good first issue

#14 fix
  index.html
Labels: bug

#15 fix
  index.html
Labels: bug

#25 add feed UI
  CSS/base.css
  CSS/index.css
  index.html
  js/base.js
Labels: enhancement

#27 update feed UI for desktop devices
  CSS/base.css
Labels: enhancement

#29 Disable spellcheck on Feed page text-areas
  index.html
Labels: enhancement, good first issue

#34 fix merge conflicts and remove team info from feed
  index.html
Labels: enhancement, good first issue

#40 adjust poem UI in feed page (index.html)
  CSS/base.css
  index.html
  js/poems.js
Labels: bug, enhancement, good first issue

#56 Link Login page to API
  CSS/base.css
  js/bootstrap/bootstrap.bundle.js
  js/bootstrap/bootstrap.bundle.js.map
  js/bootstrap/bootstrap.bundle.min.js
  js/bootstrap/bootstrap.bundle.min.js.map
  js/bootstrap/bootstrap.js
  js/bootstrap/bootstrap.js.map
  js/bootstrap/bootstrap.min.js
  js/bootstrap/bootstrap.min.js.map
  js/login.js
  login.html
Labels: enhancement

#60 fetch poems
  js/poems.js
Labels: enhancement

#61 added dark mode
  CSS/base.css
  index.html
  js/base.js
Labels: enhancement

#62 [NEW] signup - API integration
  js/signup.js
  signup.html
Labels: enhancement

#64 Remove whitespace from each poem in Feed page
  js/poems.js
Labels: bug

#67 Fixing Patch
  HTML/formulario.html
  SeusPoemas.html
  js/login.js
  js/poems.js
  js/signup.js
  login.html
  poem.html
  signup.html
Labels: bug

#66 :recycle: refactor navbar style
  CSS/base.css
  index.html
Labels: hacktoberfest-accepted

#74 fix getPostDataForPoemAddiction bug at addPoem.js
  js/addPoem.js
Labels: bug, hacktoberfest-accepted

#75 Improved addPoem.html UI
  CSS/addPoem.css
  CSS/base.css
  addPoem.html
  js/darkmode.js
Labels: enhancement, hacktoberfest-accepted

#76 Persistent Dark Mode System & UI adjustment
  CSS/base.css
  CSS/login.css
  CSS/signup.css
  index.html
  js/base.js
  js/darkmode.js
  login.html
  signup.html
Labels: enhancement, hacktoberfest-accepted

#84 Turn navbar title into link to feed page & makes navbar links more consistent in Feed page
  CSS/base.css
  addPoem.html
  index.html
  login.html
  signup.html
Labels: enhancement, hacktoberfest-accepted

#85 Make navbar's links more minimalist
  addPoem.html
  login.html
  signup.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#88 feat: fix addPoem.js's empty fields bug
  js/addPoem.js
Labels: bug, hacktoberfest-accepted

#89 add scroll pagination to feed page (index.html)
  index.html
  js/poems.js
Labels: enhancement, hacktoberfest-accepted

#91 feat: fix infinite scroll bug at poems.js
  js/poems.js
Labels: bug, hacktoberfest-accepted

#92 Remove login/logout buttons from navbar when necessary
  addPoem.html
  js/base.js
  js/signup.js
  signup.html
Labels: enhancement, hacktoberfest-accepted

#94 Show author's username instead of _id in poems
  js/poems.js
  signup.html
Labels: enhancement

#95 Make poem editing button only appear for owned poems
  js/login.js
  js/logout.js
  js/poems.js
Labels: enhancement

#97 add poem editing mechanism in feed page
  CSS/base.css
  js/login.js
  js/poems.js
Labels: enhancement, hacktoberfest-accepted

#100 feat: heart icon
  js/poems.js
Labels: enhancement, hacktoberfest-accepted

#102 Show real hearts at feed page
  CSS/base.css
  js/poems.js
Labels: enhancement

#103 [NEW] - #98 - link to addpoem.html
  index.html
  js/base.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#104 show full hearts when client has given a heart to the poem
  js/poems.js
Labels: enhancement

#105 add heart taking back system at feed page
  index.html
  js/poems.js
Labels: enhancement, hacktoberfest-accepted

#106 Project cleaning
  CSS/css_bootstrap/bootstrap-grid.css
  CSS/css_bootstrap/bootstrap-grid.css.map
  CSS/css_bootstrap/bootstrap-reboot.css
  CSS/css_bootstrap/bootstrap-reboot.css.map
  CSS/css_bootstrap/bootstrap.css
  CSS/css_bootstrap/bootstrap.css.map
  SeusPoemas.html
  Suporte.html
  addPoem.html
  formulario.html
  images/arte.png
  images/pre_logo.png
  index.html
  js/addPoem.js
  js/base.js
  js/bootstrap/bootstrap.bundle.js
  js/bootstrap/bootstrap.js
  js/darkmode.js
  js/data.json
  js/login.js
  js/logout.js
  js/poems.js
  js/signup.js
  login.html
  poem.html
  signup.html
Labels: enhancement

#108 Fix poem editing function at poem.js
  js/poems.js
Labels: bug

#110 Fix giveHeart and loadMore functions at poems.js
  js/poems.js
Labels: bug

#111 Fix infinite scroll for IOS
  js/poems.js
Labels: bug

#109 Add loading animation whilst waiting for the poems to be fetched
  CSS/base.css
  index.html
  js/poems.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#112 Fix showPoems function
  js/poems.js
Labels: bug

#118 Add trendings to Feed page
  CSS/base.css
  js/poems.js
Labels: enhancement

#119 Fix trending
  js/poems.js
Labels: bug

#121 Fix broken trending to unauthenticated users
  js/poems.js
Labels: bug

#127 Fix UI for unauthorized users in index.js and poems.js
  js/poems.js
Labels: bug
